apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: build-suite-test-component-image-source-wxud
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: build-suite-test-component-image-source-wxud
    app.kubernetes.io/part-of: test-app-ecpy
  name: build-suite-test-component-image-source-wxud
  namespace: build-e2e-muby-tenant
spec:
  ports:
  - port: 8081
    targetPort: 8081
  selector:
    app.kubernetes.io/instance: build-suite-test-component-image-source-wxud
status:
  loadBalancer: {}
